
"""
Generated by airflow console
fileName:  elbs/2_first.py
date    :  2019-09-19 18:04:48
"""


from airflow import DAG
from datetime import datetime

default_args = {
    'owner': 'sdfsdf',
    'depends_on_past': False,
    'start_date': datetime(2019, 09, 18),
}

dag = DAG(
    '2_first',
    description='sdffsdfs',
    default_args=default_args,
    schedule_interval="sdfsdf")


from airflow.operators.bash_operator import BashOperator






aa = BashOperator(
    task_id='aa',
    bash_command='date',
    dag=dag)






bb = BashOperator(
    task_id='bb',
    bash_command='echo \'Hello Ryan\'',
    dag=dag)


aa << bb